### ISSUE TITLE
Add linkout to VariantMatcher

### ISSUE THREAD

**Issue by julsera** [LiuzLab/MARRVEL2#15]
Another resource that we can link out to, simliar to how we plan to link out to MyGene2: Dear GeneMatcher user, We are writing to let you know about VariantMatcher (variantmatcher.org), a new data sharing tool that we have developed. VariantMatcher is a freely accessible web site developed as part of the Baylor-Hopkins Center for Mendelian Genomics (BHCMG). VariantMatcher is designed to enable connections between patients, their families, clinicians, and researchers from around the world with the BHCMG collaborators through a common interest in the same genomic coordinate(s). The principal goal for making VariantMatcher available is to help solve 'unsolved' exomes and genomes. This may be done with cases from research or clinical sources.
VariantMatcher allows individuals to post a genomic coordinate(s) of interest and will connect them to participants of the BHCMG project with interest in the same variant(s). Users will create an account and submit genomic coordinate(s) of interest. The matching process is automatic. When a match occurs, both parties will automatically receive an email notification. Follow-up is at the discretion of both parties. If a match is not identified at the time of submission, the genomic coordinate(s) of interest can be stored in the database for future queries. VariantMatcher adheres to strict safety and privacy protocols. Users must register and be approved to use the site. The database is not searchable and does not collect or evaluate identifiable data. Users may not access the full database.

**Comment by arine** [comment]
Where and in what form do I we want to put this link?

**Comment by julsera** [comment]
Provide a linkout "https://variantmatcher.org/" next to MyGene2
with the blurb:
"VariantMatcher is a freely accessible web site developed as part of the Baylor-Hopkins Center for Mendelian Genomics (BHCMG). The principal goal for making VariantMatcher available is to help solve 'unsolved' exomes and genomes. This may be done with cases from research or clinical sources. Users must register and be approved to use the site."
