### ISSUE TITLE
PHAROS data missing for NOTCH1

### ISSUE THREAD

**Issue by julsera** [LiuzLab/MARRVEL2#21]
"No Data found" for PHAROS on http://marrvel.org:8080/human/gene/4851.

But there are 18 ligands:
https://pharos.nih.gov/targets/NOTCH1

![image](https://user-images.githubusercontent.com/26509551/70736013-ffe40700-1cd4-11ea-9a56-a8fde01ff2b4.png)

**Comment by arine** [comment]
Modified script requesting PHAROS target and initiated the update
