### ISSUE TITLE
How is the average dbNSFP rank score computed? 

### ISSUE THREAD

**Issue by MGCarta** [LiuzLab/MARRVEL2#44]
Hi, I have been using the MARRVEL database for a short time and I would like to integrate the MARRVEL2 API in my pipeline in order to get the average dbNSFP rank score. 
However, this is not an issue but rather it´s more a doubt: I was wondering what does the average dbNSFP rank score in the MARRVEL website represent and how is computed.
I have already got the dbNSFP scores from the MARRVEL2 API but if I compute the average of all the rank scores (they are approx 24 scores) it doesn´t match that displayed in the website. 
Then I was wondering if the average dbNSFP rank score displayed is computed based on the all reported scores of if there is something I´m not getting. 

Thank you in advance, 
Giulia

**Comment by arine** [comment]
Opened issue #45
